name: PertSets
checkpoint: null
device: cuda

kwargs:
  cell_set_len: 256
  blur: 0.05
  hidden_dim: 1488  # hidden dimension going into the transformer backbone
  loss: energy
  freeze_pert_backbone: True
  confidence_head: False
  n_encoder_layers: 4
  n_decoder_layers: 4
  predict_residual: True
  softplus: True
  freeze_pert: False
  transformer_decoder: False
  finetune_vci_decoder: False
  residual_decoder: False
  batch_encoder: False
  nb_decoder: False
  mask_attn: False
  use_effect_gating_token: False
  distributional_loss: energy
  gene_decoder_bool: True
  init_from: /home/wyunzhe/projects/state/tahoe_final.ckpt
  transformer_backbone_key: llama
  transformer_backbone_kwargs:
      max_position_embeddings: 256
      hidden_size: 1488
      intermediate_size: 5952
      num_hidden_layers: 6
      num_attention_heads: 12
      num_key_value_heads: 12
      head_dim: 124
      use_cache: false
      attention_dropout: 0.0
      hidden_dropout: 0.0
      layer_norm_eps: 1e-6
      pad_token_id: 0
      bos_token_id: 1
      eos_token_id: 2
      tie_word_embeddings: false
      rotary_dim: 0
      use_rotary_embeddings: false
